name: Get new request

on:
  issues:
    types: [closed]

jobs:
  search:
    runs-on: windows-latest
    env:
      Github_personal_token: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.2.0
      - name: Authenticate with GitHub
        run: |
          Install-Module PowerShellForGitHub -Force -ErrorAction SilentlyContinue
          Import-Module PowerShellForGitHub
          $cred = New-Object System.Management.Automation.PSCredential "anything", ${{ secrets.GITHUB_TOKEN }}
          Set-GitHubAuthentication -Credential $cred
          $cred = $null
        shell: pwsh
      - name: Check requests
        run: |
          Import-Module PowerShellForGitHub
          Set-GitHubConfiguration -DisableTelemetry
          & "${{ github.workspace }}\tools\looknewer.ps1"