name: Get new request

on:
  issues:
    types: [closed]

jobs:
  search:
    runs-on: windows-latest
    env:
      Github_personal_token: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.2.0
      - name: Authenticate with GitHub
        run: |
          Install-Module PowerShellForGitHub -Force -ErrorAction SilentlyContinue
          Import-Module PowerShellForGitHub
          $tokenEncrypted = ConvertTo-SecureString -String ${{ secrets.GITHUB_TOKEN }} -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential "anything", $tokenEncrypted
          Set-GitHubAuthentication -Credential $cred
          $cred = $null
        shell: pwsh
      - name: Check requests
        run: |
          Import-Module PowerShellForGitHub
          Set-GitHubConfiguration -DisableTelemetry
          Set-Location ${{ github.workspace }}
          & ".\tools\looknewer.ps1"
      - name: Get new package
        run: |
          Import-Module "${{ github.workspace }}\scripts\new.psm1"
          Set-Location ${{ github.workspace }}
          Find-nextissueGH -packageName "${{ github.event.issue.title }}" -actor "tunisiano187"